sudo: false

env:
  - DOCKER_COMPOSE_VERSION=1.19.0

language: python
python:
  - "3.6"

services:
  - docker

before_install:
  - docker-compose pull
  - docker-compose build --no-cache
  - docker-compose up --force-recreate -d
  - docker-compose logs
  - docker-compose ps

script:
  - curl -Ifs http://localhost
  - curl -Ifs http://localhost/blog